apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: picalc-pr-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: gitUrl
      value: https://github.com/IBM/tekton-tutorial.git
    - name: gitRevision
      value: beta-update
    - name: pathToYamlFile
      value: "kubernetes/picalc.yaml"
    - name: imageUrl
      value: 147803190433.dkr.ecr.eu-central-1.amazonaws.com/container-images
    - name: imageTag
      value: "1.0"
  serviceAccountName: pipeline-account
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: picalc-source-pvc
