apiVersion: apps/v1
kind: Deployment
metadata:
  name: picalc
  namespace: minnova-dev
  labels:
    app: picalc
spec:
  selector:
    matchLabels:
      app: picalc
  revisionHistoryLimit: 0 
  template:
    metadata:
      labels:
        app: picalc
    spec:
      containers:
      - name: picalc
        image: __IMAGE__@__DIGEST__
        ports:
        - name: http-server
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: picalc
  namespace: minnova-dev
  labels:
    app: picalc
spec:
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: picalc
  type: ClusterIP

---           
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo.keen.world
  annotations:
    nginx.ingress.kubernetes.io/app-root: $uri
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "20s"
    nginx.org/client-max-body-size: "4m"
    namespace: minnova-dev
spec:
  ingressClassName: nginx
  rules:
  - host: picalc.keen.world
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: picalc
            port: 
              number: 80
